### ISSUE TITLE
can't use ios 5, used autolayout

### ISSUE THREAD

**Issue by xiongcaixing1986** [ealeksandrov/EAIntroView#101]

**Comment by ealeksandrov** [comment]
Latest version - [2.7.0](https://github.com/ealeksandrov/EAIntroView/releases/tag/2.7.0) should work for you. Only `:head` contains 81c1f612f3c8c8dbbc434e55b1436d68de60b54b and 7b245c11fa3f5159f2a38de0b70f6273ec223ab9, that added explicit dependency on autolayout.
