### ISSUE TITLE
'pod install' fails for the example project

### ISSUE THREAD

**Issue by christophefondacci** [ealeksandrov/EAIntroView#104]
What I did:
* `git clone https://github.com/ealeksandrov/EAIntroView`
* Go into EAIntroView/Example
* `pod install`

Here is the output from cocoapods:
 
    Analyzing dependencies
    Fetching podspec for `EAIntroView` from `../`
    [!] Unable to satisfy the following requirements:
    
    - `EAIntroView (from `../`)` required by `Podfile`
    - `EAIntroView (from `../`)` required by `Podfile`
    - `EAIntroView (= 2.6.4)` required by `Podfile.lock`

I tried removing the reference to '../' in the podfile and replacing it by '~> 2.7.0' which does work but then the Xcode build from the workspace fails with again some references to '../'.

Everything else (referencing the lib from another project) works fine but I cannot run the example.

**Comment by christophefondacci** [comment]
Ok I found the problem.
=> You should not commit 'Podfile.lock' and add it to .gitignore. 

A good thing would also to add `Pods/` to gitignore
Thank you for the framework!

**Comment by ealeksandrov** [comment]
Thanks for information and way to fix, will look into it!

**Comment by ealeksandrov** [comment]
Can you verify this on latest version of `EAIntroView` and `cocoapods`?
My `pod install` output is fine:
![screenshot 2015-04-26 22 56 33](https://cloud.githubusercontent.com/assets/3132438/7338996/a47ff3a8-ec67-11e4-91c6-3556a732029c.png)

**Comment by ealeksandrov** [comment]
Extremely strange, I'm getting your error now. Probably have to remove `Podfile.lock`.

**Comment by ealeksandrov** [comment]
My mistake, I should run `pod update` for example project on every podspec update.
Fixed in 8f63ee170bcdb6859879c5eccc2430e69813ddb5

**Comment by christophefondacci** [comment]
I confirm: everything works fine now
