### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by kohtenko** [ealeksandrov/EAIntroView#109]
Could you update your podspec and tags? Cause now in latest tag (2.7.0) code are older then in master branch. And latest changes are definitely necessary :)

**Comment by ealeksandrov** [comment]
There are a number of critical bugs in current code, have to deal with them first.
Going to finish it on this week.

**Comment by ealeksandrov** [comment]
I fixed a number of issues and pushed 2.7.1 version on Cocoapods.
There will be significant bug fixes (related with xibs and autolayout) and more updates soon.

**Comment by ealeksandrov** [comment]
2.7.2 and 2.7.3 was created struggling with #104 & #107 - just `Example` project maintenance.
2.7.3 is the best for now :)
