### ISSUE TITLE
Linker Errors When Building

### ISSUE THREAD

**Issue by dhint4** [ealeksandrov/EAIntroView#111]
Anytime I try to build a project, I get these linker errors:

    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_EAIntroPage", referenced from:
          objc-class-ref in VHFirstExpierienceController.o
      "_OBJC_CLASS_$_EAIntroView", referenced from:
          objc-class-ref in VHFirstExpierienceController.o
    ld: symbol(s) not found for architecture x86_64
     clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is my code:

    #import "VHFirstExpierienceController.h"
    #import "EAIntroView.h"

    @interface VHFirstExpierienceController () <EAIntroDelegate>

    @end

    @implementation VHFirstExpierienceController

    -(instancetype)init{
    
        if (self = [super init]) {
            [self setup];
        }
    
        return self;
    }

    -(void)setup{
        [self createPages];
    }

    -(void)createPages{
    
        EAIntroPage *page1 = [EAIntroPage page];
        page1.title = @"Title";
        page1.desc = @"Desc";
    
        EAIntroView *intro = [[EAIntroView alloc] initWithFrame:self.view.bounds andPages:@[page1]];
        intro.delegate = self;
    
        [intro showInView:self.view animateDuration:1.0];
    }

Any ideas on why it won't build?

**Comment by dhint4** [comment]
Manually adding these to the `Other Linker Flags` section in the build settings fixed the problem
    -l"Pods-EARestrictedScrollView"
    -l"Pods-EAIntroView"

Any idea why these were not automatically added?

**Comment by ealeksandrov** [comment]
Something wrong with your Cocoapods setup.

Just tried to create fresh project, added `pod 'EAIntroView'` and imported in view controller - and it works ok.

**Comment by Omarj** [comment]
@ealeksandrov I did what you ask for but still does not work ??

@dhint4  not even your solution ?
