### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by temasnow** [ealeksandrov/EAIntroView#114]
Приветствую,
Не нашел возможности настроить прозрачность view между фоновым изображением и контентом страницы (Page).
То есть, требуется, чтобы выглядело так:
![screen shot 2015-04-06 at 13 38 13](https://cloud.githubusercontent.com/assets/3713547/7982496/432eee16-0ac0-11e5-9076-406a8e83c2d9.png)
а получается так:
![ios simulator screen shot 04 jun 2015 13 49 52](https://cloud.githubusercontent.com/assets/3713547/7982538/98df26e6-0ac0-11e5-970e-8452edf4f7ef.png)

**Comment by ealeksandrov** [comment]
Фоновое изображение - page или introView?

**Comment by temasnow** [comment]
```page.bgImage```

**Comment by ealeksandrov** [comment]
Возвращаясь к этой проблеме - тут не настройка прозрачности, а добавление оверлея поверх фонового изображения с целью повышения читаемости текста. Этот feature request обсуждается в #118 и будет добавлен в следующих версиях. Скорее всего будет вариант добавления blurring и fading. В данном примере достаточно добавить fading.

Closing as duplicate, discussion of background image fading will be continued in #118.
