### ISSUE TITLE
How to hide or show status bar?

### ISSUE THREAD

**Issue by Voley** [ealeksandrov/EAIntroView#116]
Topic. How do I hide or show status bar? Didn't find anywhere, but that would be a great feature.
Regards

**Comment by Omarj** [comment]
@Voley  you can hide it if in your application didFinishLaunchingWithOptions or before u show your tutorial using :

[[UIApplication sharedApplication] setStatusBarHidden:YES];

**Comment by ealeksandrov** [comment]
It really more depends on application, as @Omarj described. We can't override status bar in UIView when "View controller-based status bar appearance" set to YES.
