### ISSUE TITLE
Tap to next is not applied on custom view

### ISSUE THREAD

**Issue by maxep** [ealeksandrov/EAIntroView#119]
Hi @ealeksandrov,

The ```tapToNext``` doesn't seem to have an effect on custom page.

**Comment by ealeksandrov** [comment]
We can't know view hierarchy for any custom page. Maybe I will add tapToNext button beneath of all subviews in custom view, this will work for most of use cases.

**Comment by maxep** [comment]
Hi, thanks for your response.

Yes you are right. Maybe you can use the ```gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:``` method from UIGestureRecognizerDelegate to catch the tap on subviews..

**Comment by Woildan** [comment]
I've looked at the code and right now tap to next is handle using a transparent UIButton.

Maybe it'd be better to handle tap to next using a gesture recognizer on the page root view. This way it could work for custom pages and avoids touching the view hierarchy. It should work as long as touch events are not captured by an intermediary view (in which case we can only suppose it's a good thing the intro doesn't go to next page).

**Comment by maxep** [comment]
Yes, thats would be a good solution.

**Comment by ealeksandrov** [comment]
Closed by #175
