### ISSUE TITLE
I would like to show the Skip button on all pages except the last.

### ISSUE THREAD

**Issue by jalsop** [ealeksandrov/EAIntroView#126]
I will have a custom button on the last page, so don't need or want the Skip button.
If the user scrolls back to a previous page, the Skip button should reappear.

Is this possible?

**Comment by ealeksandrov** [comment]
Yep, it is already implemented in [demo project](https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L243-L257): 

```
// show skipButton only on 3rd page + animation

    intro.skipButton.alpha = 0.f;
    intro.skipButton.enabled = NO;
    page3.onPageDidAppear = ^{
        intro.skipButton.enabled = YES;
        [UIView animateWithDuration:0.3f animations:^{
            intro.skipButton.alpha = 1.f;
        }];
    };
    page3.onPageDidDisappear = ^{
        intro.skipButton.enabled = NO;
        [UIView animateWithDuration:0.3f animations:^{
            intro.skipButton.alpha = 0.f;
        }];
    };
```

This will show skip button only on 3rd page and hide on all others. Invert this logic to hide button only on last page.

**Comment by jalsop** [comment]
Perfect - thanks!


- John Alsop
