### ISSUE TITLE
TestTarget throws a lot of warnings

### ISSUE THREAD

**Issue by ogezue** [ealeksandrov/EAIntroView#137]
I'm using XCode 7, iOS9 as target and Swift and everything is working fine.
But my testtarget throws a lot of errrors. I don't do enything with your lib in tests.

My podfile contains the line
link_with 'AppName', 'AppNameTests' to make your lib working with my project. Perhaps this has something to do with it.

(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/ObjectiveC-2CD0WTQVXITO7.pcm: No object file for requested architecture
(null): warning: Could not resolve external type c:objc(cs)NSObject
(null): warning: Could not resolve external type c:objc(cs)UIImage
(null): warning: Could not resolve external type c:objc(cs)UIColor
(null): warning: Could not resolve external type c:objc(cs)UIView
(null): warning: Could not resolve external type c:objc(cs)NSString
(null): warning: Could not resolve external type c:objc(cs)UIFont
(null): warning: Could not resolve external type c:objc(cs)NSArray
(null): warning: Could not resolve external type c:objc(cs)NSBundle
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/CoreGraphics-1YQ59ILDR3NYI.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/CoreGraphics-1YQ59ILDR3NYI.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Dispatch-12O7S7HHQXK9N.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/ObjectiveC-2CD0WTQVXITO7.pcm: No object file for requested architecture
(null): warning: Could not resolve external type c:objc(cs)UIView
(null): warning: Could not resolve external type c:objc(cs)UIView
(null): warning: Could not resolve external type c:objc(cs)UIImage
(null): warning: Could not resolve external type c:@E@UIViewContentMode
(null): warning: Could not resolve external type c:objc(cs)UIPageControl
(null): warning: Could not resolve external type c:objc(cs)UIButton
(null): warning: Could not resolve external type c:objc(cs)UIScrollView
(null): warning: Could not resolve external type c:objc(cs)NSArray
(null): warning: Could not resolve external type c:@S@CGPoint
(null): warning: Could not resolve external type c:@S@CGRect
(null): warning: Could not resolve external type c:objc(cs)UIImageView
(null): warning: Could not resolve external type c:objc(cs)NSMutableArray
(null): warning: Could not resolve external type c:objc(cs)NSObject
(null): warning: Could not resolve external type c:objc(cs)UIColor
(null): warning: Could not resolve external type c:objc(cs)NSString
(null): warning: Could not resolve external type c:objc(cs)UIFont
(null): warning: Could not resolve external type c:@S@CGSize
(null): warning: Could not resolve external type c:objc(cs)NSCoder
(null): warning: Could not resolve external type c:objc(cs)NSAttributedString
(null): warning: Could not resolve external type c:objc(cs)UILabel
(null): warning: Could not resolve external type c:objc(cs)UITextView
(null): warning: Could not resolve external type c:objc(cs)NSDictionary
(null): warning: Could not resolve external type c:objc(cs)UIInterpolatingMotionEffect
(null): warning: Could not resolve external type c:objc(cs)UIMotionEffectGroup
(null): warning: Could not resolve external type c:objc(cs)NSEnumerator
(null): warning: Could not resolve external type c:objc(cs)UIWindow
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/UIKit-2LM3EQU7VVY4O.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/Foundation-A3SOD99KJ0S9.pcm: No object file for requested architecture
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/CoreGraphics-1YQ59ILDR3NYI.pcm: No such file or directory
(null): warning: /Users/username/Library/Developer/Xcode/DerivedData/ModuleCache/284YBPN2V00YK/CoreGraphics-1YQ59ILDR3NYI.pcm: No object file for requested architecture
(null): warning: Could not resolve external type c:objc(cs)UIScrollView
(null): warning: Could not resolve external type c:objc(cs)NSArray
(null): warning: Could not resolve external type c:@S@CGPoint
(null): warning: Could not resolve external type c:@S@CGRect
(null): warning: Could not resolve external type c:objc(cs)UIView
(null): warning: Could not resolve external type c:@S@CGSize

**Comment by ogezue** [comment]
it is gone with XCode 7.1

**Comment by SquaredTiki** [comment]
Still seeing this in Xcode 7.1 myself.
