### ISSUE TITLE
Bridging-Header  EAIntroView.h file not found

### ISSUE THREAD

**Issue by chlebta** [ealeksandrov/EAIntroView#143]
Hello, I've tried to use this library manually and via pods in swift project but I get always same error **"EAIntroView.h file not found** at this line `#import "EAIntroView.h"` in the bridging file.

**Comment by ealeksandrov** [comment]
There are 2 ways to use `EAIntroView` in Swift project: as a module or importing through bridging header.

Here is importing it in a bridging header:

![screenshot 2015-12-03 22 16 09](https://cloud.githubusercontent.com/assets/3132438/11571220/4a4ea53e-9a0c-11e5-82cb-8157bc751286.png)

And here is using it as a module, you need to add `use_frameworks!` to your `Podfile`:

![screenshot 2015-12-03 22 19 46](https://cloud.githubusercontent.com/assets/3132438/11571228/5b11fdee-9a0c-11e5-8195-9385b40910d6.png)
