### ISSUE TITLE
setCurrentPageIndex does not set _currentPageIndex

### ISSUE THREAD

**Issue by sebastianludwig** [ealeksandrov/EAIntroView#144]
This makes resetting and reusing an `EAIntroView` impossible. `_currentPageIndex = currentPageIndex;` in `-setCurrentPageIndex:animated:` fixes the issue.

**Comment by polegithub** [comment]
But , 
"scrollViewDidEndScrollingAnimation" is called when setContentOffset/scrollRectVisible:animated: finishes. not called if not animating.
So, it's a bug: _currentPageIndex cannot be changed if animation is NO.  
```
  [self setCurrentPageIndex:currentPageIndex animated:NO];
```
Can this be fixed?

**Comment by ealeksandrov** [comment]
Please take a look at linked commit, it should solve your issue. If any of problems still persists - let me know.

**Comment by sebastianludwig** [comment]
I didn't try it out yet, but doesn't the current implementation leave `_currentPageIndex` at its old value until the scroll view did end decelerating (whenever that might be) when calling `[introView setCurrentPageIndex:? animated:YES]`? This would be a rather unusual behavior for an UIKit component. Normally the initial state is effected immediately not after the animation has finished (`UITabBarController.selectedIndex`, `UINavigationController.topViewController`, ...).

In general, not setting the backing ivar in a setter feels odd.

**Comment by ealeksandrov** [comment]
I was afraid that setting `_currentPageIndex` before animation can result in undesired behaviour during scroll animation. But after looking over the code and testing it, I will agree with your arguments.

Related commit: a5ce2c3336f4dfbc3cc1a02ef3ba9f8272fd9be6

**Comment by sebastianludwig** [comment]
Looks great, thank you very much for fixing this issue! :+1:
