### ISSUE TITLE
library not found for -lEAIntroView (Manual installation)

### ISSUE THREAD

**Issue by polegithub** [ealeksandrov/EAIntroView#145]
Create a file called :EAIntroView:
Add EAIntroPage and EAIntroView headers and implementations  (4 files total).
Add EARestrictedScrollView header and implementation  (2 files total).

but when build project ,has error : 
```
ld: library not found for -lEAIntroView
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ealeksandrov** [comment]
While testing I have one problem: changing `#import <EARestrictedScrollView/EARestrictedScrollView.h>` to `#import "EARestrictedScrollView.h"`
But I can't see issue with `ld: library not found for -lEAIntroView`
