### ISSUE TITLE
Fail import on swift ?

### ISSUE THREAD

**Issue by tirrorex** [ealeksandrov/EAIntroView#146]
Hello, i got no such module message after installing the pod and adding import EAIntroView to my file.
Did i miss something or is it a bug?

**Comment by ealeksandrov** [comment]
There are 2 ways to use `EAIntroView` in Swift project: as a module or importing through bridging header.

Here is importing it in a bridging header:

![screenshot 2015-12-03 22 16 09](https://cloud.githubusercontent.com/assets/3132438/11571220/4a4ea53e-9a0c-11e5-82cb-8157bc751286.png)

And here is using it as a module, you need to add `use_frameworks!` to your `Podfile`:

![screenshot 2015-12-03 22 19 46](https://cloud.githubusercontent.com/assets/3132438/11571228/5b11fdee-9a0c-11e5-8195-9385b40910d6.png)

**Comment by tirrorex** [comment]
Tried both, none of it was working actually, that was the reason behing my
issue

2015-12-03 20:23 GMT+01:00 Evgeny Aleksandrov <notifications@github.com>:

**Comment by ealeksandrov** [comment]
Do a clean and delete derived data :) Can't say any more than that.

**Comment by Evilcome** [comment]
It's not works when import, xcode can not build EAIntroView framework success because in `EAIntroView.h` file not found when #import "EARestrictedScrollView.h". 
Your example project works, but var `pod install` fail.

**Comment by ealeksandrov** [comment]
I took these example screenshots after creating new project in Xcode, adding pod file and running `pod install`. They are not related with bundled example project in any way.
