### ISSUE TITLE
Compile error in XCode while fetching EAIntroView through Pod

### ISSUE THREAD

**Issue by stone12379** [ealeksandrov/EAIntroView#147]
**"EARestrictedScrollView.h" not found error** raised by XCode due to improper setting in "EAIntroView.h".
Resolved after changing the import sentence from **#import "EARestrictedScrollView.h"** to **#import "EARestrictedScrollView/EARestrictedScrollView.h"** in **EAIntroView.h**

**Comment by NitWitStudios** [comment]
I had this same problem and this was also the solution for me. Using EAIntroView cocoapod in a Swift 2.0 project. Please fix in master.

**Comment by ealeksandrov** [comment]
Please check out #148

**Comment by stone12379** [comment]
I guess the reason both @NitWitStudios and I encountered the error is that we both use Swift 2.0 as our project language. @ealeksandrov, could you please confirm that?

**Comment by ealeksandrov** [comment]
I am using latest Xcode 7.2 and latest CocoaPods 0.39.0
