### ISSUE TITLE
Compile error in XCode while fetching EAIntroView through Pod

### ISSUE THREAD

**Issue by stone12379** [ealeksandrov/EAIntroView#148]
**"EARestrictedScrollView.h"** not found error raised by XCode due to improper setting in "EAIntroView.h".
Resolved after changing the import sentence from **#import "EARestrictedScrollView.h"** to **#import "EARestrictedScrollView/EARestrictedScrollView.h"** in EAIntroView.h

**Comment by ealeksandrov** [comment]
Tried on fresh new project with EAIntroView 2.8.0 from Pods - it worked flawlessly:

![screenshot 2015-12-09 12 57 33](https://cloud.githubusercontent.com/assets/3132438/11682261/b55a54b0-9e74-11e5-8dad-15732be34130.png)

**Comment by stone12379** [comment]
![image](https://cloud.githubusercontent.com/assets/10493864/11767294/be9b0304-a1e3-11e5-9433-3eeedf103e1c.png

**Comment by stone12379** [comment]
![2015-12-13 9 53 23](https://cloud.githubusercontent.com/assets/10493864/11767299/f95b0ac0-a1e3-11e5-9ac3-e397e8f28b58.png)

**Comment by stone12379** [comment]
Still, I am saying that if you try to create a swift2 project and using Pods to integrate EAIntroView, you will see the error by yourself.

**Comment by ealeksandrov** [comment]
Please share your Xcode version (`Xcode - about Xcode`) and CocoaPods version (`pod --version`)

**Comment by stone12379** [comment]
Xcode 7.2(7C68) pod (0.39.0)

**Comment by CodeEagle** [comment]
#import "EARestrictedScrollView.h" error

**Comment by RafaelKayumov** [comment]
For me builds fine on Xcode Version 7.2 (7C68), pod 0.39.0.

**Comment by Gargam** [comment]
Same here not working with the same error on Swift 2 project

**Comment by xrelative** [comment]
same error

**Comment by ealeksandrov** [comment]
Please drop me minimal demo project, since I can't reproduce it locally.
I don't want to simply change import statement because <EARestrictedScrollView/EARestrictedScrollView.h> will 100% introduce issues for manual install.

**Comment by stone12379** [comment]
Here is my project files. To redo it by yourself, you need to create a brand new swift 2 project with pods and create a bridging-header file and import EAIntroView.h.


Date: Tue, 15 Dec 2015 13:06:22 -0800

**Comment by ealeksandrov** [comment]
Already pushed and deployed 3.8.1 yesterday :)
