### ISSUE TITLE
Issues preventing scroll from going past last view

### ISSUE THREAD

**Issue by tunds** [ealeksandrov/EAIntroView#152]
I'm having issues preventing the view from scrolling past the last view, if the user scrolls pasts the last view they're presented with the original viewcontroller that it's attached too. 

Here's is the code that i'm using to prevent this from happening.

```
    func setUpIAPOptions(){

        let welcomePage = EAIntroPage(customViewFromNibNamed: "welcomeIAPView")
        let firstIAPPage = EAIntroPage(customViewFromNibNamed: "firstIAPView")
        let secondIAPPage = EAIntroPage(customViewFromNibNamed: "secondIAPView")
        let thirdIAPPage = EAIntroPage(customViewFromNibNamed: "thirdIAPView")
        
        // CREATE BUTTON ACTIONS
        let options = EAIntroView(frame: self.view.bounds, andPages: [welcomePage,firstIAPPage,secondIAPPage,thirdIAPPage])
        
        options.addSubview(createDismissButton(self.view))
        
        options.skipButton.enabled = false
        options.skipButton.alpha = 0
        
        // Here i'm trying to prevent the scroll from going past the last page, the 4th one  
        options.limitScrollingToPage(3)
        
        options.delegate = self
        
        let firstIAPBtn = firstIAPPage.pageView.viewWithTag(1) as! SpringButton
        firstIAPBtn.addTarget(self, action: "firstIAPSelected:", forControlEvents: .TouchUpInside)
        
        let secondIAPBtn = secondIAPPage.pageView.viewWithTag(1) as! SpringButton
        secondIAPBtn.addTarget(self, action: "secondIAPSelected:", forControlEvents: .TouchUpInside)
        
        let thirdIAPBtn = thirdIAPPage.pageView.viewWithTag(1) as! SpringButton
        thirdIAPBtn.addTarget(self, action: "thirdIAPSelected:", forControlEvents: .TouchUpInside)
        
        options.showInView(self.view)
        
    }
```

Screenshots attached. 

![img_5577](https://cloud.githubusercontent.com/assets/13179531/11893749/c0214ef6-a56a-11e5-90b3-cb8accd52deb.PNG)
![img_5578](https://cloud.githubusercontent.com/assets/13179531/11893748/c01e2294-a56a-11e5-83c2-8d8822d1e17b.PNG)

**Comment by Moyasengit** [comment]
Hmm.. You are not suppose to change the original code but if you look in the file EAIntroView.m you search for"swipeToExit".

I think in line 61 there is "self.swipeToExit = YES;"
Set that to NO and it will not swipe to exit! 

Sincerely

**Comment by tunds** [comment]
Is there a way to access this property from my VC? Since i'm using cocoapods and if this repo gets updated it will revert it back to it's previous value.

**Comment by Moyasengit** [comment]
hmm... cal it from your VC where you have your code already. the instance of theEAIntroView.
Try type 

options.swipeToExit = NO;

**Comment by tunds** [comment]
Sweet that worked thanks for that :D

**Comment by Moyasengit** [comment]
Great, nice that it worked! You're welcome!
