### ISSUE TITLE
Not works in iOS8.1

### ISSUE THREAD

**Issue by amarianno** [ealeksandrov/EAIntroView#154]
I used last version 2.8.1 and my app in iOS 8.1 get crash : Thread 1: EXC_BREAKPOINT (code=EXC_I386)

after downgrade to 2.7 app works fine.

**Comment by ealeksandrov** [comment]
Can you tell what line is causing crash?

**Comment by ealeksandrov** [comment]
You can also downgrade version-by-version to narrow down changeset to debug.
Have you tried 2.8.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4?

**Comment by ealeksandrov** [comment]
Can't reproduce on iOS Simulator 8.1 and latest EAIntroView version.
After multiple test runs I seen crash or simulator launch once, but that was fixed by simple project clean.
