### ISSUE TITLE
intro.limitScrollingToIndex() not working- Swift

### ISSUE THREAD

**Issue by daisyramos317** [ealeksandrov/EAIntroView#156]
func customPage(){
        let page1 : EAIntroPage = EAIntroPage()
        page1.title = "Hello world"
        page1.titleColor = UIColor.blackColor()
        page1.desc = "Lorem ipsum dolor sit amet"
        page1.bgColor = UIColor.blueColor()
  
        let page2 : EAIntroPage = EAIntroPage()
        page2.title = "Hello world 2"
        page2.titleColor = UIColor.blackColor()
        page2.desc = "Lorem ipsum dolor sit amet 2"
        page2.bgColor = UIColor.blueColor()
      
        let intro : EAIntroView = EAIntroView(frame: self.view.bounds, andPages:[page1,page2])
        intro.delegate = self
        intro.showInView(self.view, animateDuration:0.3)
        intro.limitScrollingToPage(2)  //not working here
  
    }

This method is called in viewDidLoad()
Any suggestions would be helpful, thanks.

**Comment by ealeksandrov** [comment]
Thanks for reporting, confirmed, working on a fix.

**Comment by ealeksandrov** [comment]
Fix deployed in 2.8.3.
