### ISSUE TITLE
Cancel fade-out?

### ISSUE THREAD

**Issue by haleyngonadi** [ealeksandrov/EAIntroView#157]
Hi. This is an awesome control. I'm wondering, is it possible to have the index return to 1 instead of the titleview fade out completely? Thanks!

**Comment by ealeksandrov** [comment]
Hey!
What do you mean, "index return to 1"? Scroll to first page after last, like in #117?

**Comment by haleyngonadi** [comment]
Right. So it's impossible? :/

**Comment by ealeksandrov** [comment]
This is hard to implement with current scroll architecture, but I will certainly look more into it.
