### ISSUE TITLE
introDidFinish not called on 2.9.0

### ISSUE THREAD

**Issue by erdem-inan** [ealeksandrov/EAIntroView#167]
Hello,

I think there is an issue with the 2.9.0 version, The delegate method "introDidFinish" is not called anymore.

I worked fine on the 2.8.3 version, it start failing after I upgrade to the 2.9.0 version.
For now I fall back to the 2.8.3 version.

Could you investigate and tell me if I'am wrong.

Thanks !

**Comment by ealeksandrov** [comment]
Hey! In 2.9.0 `introDidFinish:wasSkipped:` was introduced to provide additional info to delegate: [EAIntroView.h#L28](https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroView.h#L28)

**Comment by erdemPinch** [comment]
Ok my bad, Thanks for reply so quick !

**Comment by ealeksandrov** [comment]
No problem. First place to look into in similar cases - `CHANGELOG.md` :)
Looks like we have the same issue in example project. I'll keep this issue open until I update it.

**Comment by erdemPinch** [comment]
Ok Thank for advices !
