### ISSUE TITLE
change page scrolling direction 

### ISSUE THREAD

**Issue by Amaneo** [ealeksandrov/EAIntroView#170]
is it possible to change scrolling direction to (right to left ) ?

**Comment by ealeksandrov** [comment]
You can use `setCurrentPageIndex:` to present last page, turn `swipeToExit` off, add transparent 1st page and use 1st page `onPageDidAppear` block to close intro.

**Comment by Amaneo** [comment]
well , I tried this but it didn't work. maybe I got you wrong. 

`
            intro.setCurrentPageIndex(6, animated: false)
            intro.swipeToExit = false
            page1.alpha = 0

        }
        
        page1.onPageDidAppear = {() -> Void in
            
            self.page1.alpha = 1
            self.intro.swipeToExit = true
            
        }
`

**Comment by Amaneo** [comment]
well , I tried this but it didn't work. maybe I got you wrong! 

`
            intro.setCurrentPageIndex(6, animated: false)
            intro.swipeToExit = false
            page1.alpha = 0

        }
        
            page1.onPageDidAppear = {() -> Void in
            
            self.page1.alpha = 1
            self.intro.swipeToExit = true
            
        }
`

**Comment by ealeksandrov** [comment]
Don't enable `swipeToExit` in `onPageDidAppear`. Just dismiss it straight away: `[self.intro hideWithFadeOutDuration:0.3]`.

**Comment by ealeksandrov** [comment]
Initial configuration is ok, only make sure that you're setting `page1.alpha = 0` before passing pages array to `EAIntroView` instance.
In `onPageDidAppear` add only one line `self.intro.hideWithFadeOutDuration(0.3)`. Nothing more there.
That's should be enough.

Please let me know if you still have any questions.
