### ISSUE TITLE
The EAIntroDelegate is not being called.

### ISSUE THREAD

**Issue by JeanPierreFig** [ealeksandrov/EAIntroView#173]

**Comment by JeanPierreFig** [comment]
ok go it working :) The example project I Just download uses a older version of the Delegates 

`- (void)introDidFinish:(EAIntroView *)introView wasSkipped:(BOOL)wasSkipped{}`

This one worked

**Comment by ealeksandrov** [comment]
Yeah, we should fix that :)
Closing as duplicate of #167
