### ISSUE TITLE
How to make the background transparent?

### ISSUE THREAD

**Issue by Stunner** [ealeksandrov/EAIntroView#180]
I have tried to set the `backgroundColor` to `[UIColor clearColor]` to no avail. Is this currently possible?

**Comment by saintjab** [comment]
Same problem here. Any solution @Stunner yet?

**Comment by ealeksandrov** [comment]
Simple removal of `bgImage` properties from pages of [example](https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L36-L65) show clear background color:

![simulator screen shot 18 sep 2016 18 09 38](https://cloud.githubusercontent.com/assets/3132438/18616825/9da109b0-7dd3-11e6-8fdb-f8ff0416961b.png)
