### ISSUE TITLE
Auto layouts for the iPad pro are working inappropriate .

### ISSUE THREAD

**Issue by surendraraju** [ealeksandrov/EAIntroView#181]

**Comment by surendraraju** [comment]
For those who want the fix , please let me know. I fixed it myself for my use.

**Comment by Svantulden** [comment]
Yeah please share!

**Comment by surendraraju** [comment]
EAIntroView.m , go to method -(void)willMoveToSuperview:(UIView *)newSuperview and replace the line

[[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(deviceOrientationDidChange:)
                                                     name:UIDeviceOrientationDidChangeNotification
                                                   object:nil];


with 


[[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(deviceOrientationDidChange:)
                                                     name:UIApplicationDidChangeStatusBarFrameNotification
                                                   object:nil];
