### ISSUE TITLE
Page size same as ViewController's storyboard size

### ISSUE THREAD

**Issue by tomekc** [ealeksandrov/EAIntroView#183]
Hello,
I tried using EAIntroView as outlet in storyboard. It works, but with "small" issue: when app tuns, scrollable page sizes are the same size as designed on storyboard, not the size of actual device screen. In effect, pages are misaligned (either you see fragment of next page, or other way: pages do not fit on screen).

I resolved it by creating EAIntroView programmatically and adding it to ViewController in runtime, but I am curious if I done something wrong. I tried to defer configuration to `viewWillAppear:` but it didn't help.

**Comment by ealeksandrov** [comment]
Thanks for report, I'll check this.

**Comment by rickyjwhong** [comment]
just want to say I had the same issue. Not sure what's wrong but won't work in 4 inch screen size if connected to IB, but will work if added on programmatically. fantastic pod otherwise.

**Comment by ealeksandrov** [comment]
Hmm, it is working fine for me:

![screen shot 2016-11-05 at 21 01 32](https://cloud.githubusercontent.com/assets/3132438/20032446/11d463f8-a39b-11e6-8de9-1b0b75f2c8f8.png)

**Comment by ealeksandrov** [comment]
I managed only to reproduce something like this when no autoresizing or autolayout is applied:

<img width="1445" alt="screen shot 2017-11-11 at 12 48 56" src="https://user-images.githubusercontent.com/3132438/32688271-c96639f8-c6de-11e7-9f6c-9b83b00fc831.png">

But when autolayout is applied, passing `pages` array on `viewDidLoad` results in completely correct behaviour:

<img width="1446" alt="screen shot 2017-11-11 at 12 55 39" src="https://user-images.githubusercontent.com/3132438/32688332-ba15b7e8-c6df-11e7-805c-5f2a462f44c5.png">
