### ISSUE TITLE
How to landscape/portrait

### ISSUE THREAD

**Issue by feimamura** [ealeksandrov/EAIntroView#184]
How to set an image to landscape and another image for portrait???

**Comment by ealeksandrov** [comment]
What image? There are image backgrounds, title views, custom view...

**Comment by feimamura** [comment]
yes, how to set for bgImage

**Comment by ealeksandrov** [comment]
I am not sure what are you trying to achieve, but check `bgViewContentMode` property.

**Comment by feimamura** [comment]
I'm trying to put an image to the background in case the iPad is landscape and another image if the portrait

**Comment by ealeksandrov** [comment]
1) If you want to change background image of whole intro, not 1 page - subscribe to orientation notification in your code and when notification arrives - just change `intro.bgImage`.

2) If you want to change background image of specific page - that's not simply supported by library. You can use page with `customView`, add `UIImageView` there manually with keeping reference to it and subscribe to orientation notification. When notification arrives - just change image in your custom image view.

**Comment by feimamura** [comment]
tks for help!

**Comment by ealeksandrov** [comment]
👍
