### ISSUE TITLE
EARestrictedScrollView.h not found - XCode 8 with Cocoapods 1.1.1

### ISSUE THREAD

**Issue by we7ee** [ealeksandrov/EAIntroView#187]
I'm getting error 'EARestrictedScrollView/EARestrictedScrollView.h' file not found in EAIntroView.h.

I'm using EAIntroView 2.9.0 with Xcode 8 (Version 8.0 (8A218a)) and Cocoapods v1.1.1

**Comment by ealeksandrov** [comment]
Please check out #162 
I will get back to this when I have time.

**Comment by we7ee** [comment]
Works with Swift 3, EAIntroView 2.9.0, CocoaPods 1.1.1 and "Always Search User Paths" = Yes
