### ISSUE TITLE
I've got this error after the project updating to swift 3 

### ISSUE THREAD

**Issue by soztemir** [ealeksandrov/EAIntroView#188]
Hi,
I've got this error after the project updating to swift 3

`2016-10-26 11:35:04.832709 Example[1249:237392] -[_SwiftValue alpha]: unrecognized selector sent to instance 0x170241b90
2016-10-26 11:35:04.836544 Example[1249:237392] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue alpha]: unrecognized selector sent to instance 0x170241b90'
*** First throw call stack:
(0x18d3a41c0 0x18bddc55c 0x18d3ab278 0x18d3a8278 0x18d2a259c 0x100155c3c 0x1001558f0 0x10015529c 0x10015b664 0x100153074 0x100152d9c 0x1000f7bc8 0x1000f72c4 0x1000f6c1c 0x1000f618c 0x1000f6224 0x1931ed3dc 0x1932a6fcc 0x1932a6ea4 0x1932a61ec 0x1932a5c38 0x1932a57ec 0x1932a5750 0x1931ea54c 0x1906b240c 0x1906a70e8 0x1906a6fa8 0x190623c64 0x19064b0d0 0x19064baf0 0x18d3517dc 0x18d34f40c 0x18d27e068 0x1932585dc 0x193253360 0x1000f9420 0x18c2605b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
`
Thanks
Have a nice day

**Comment by ealeksandrov** [comment]
Already discussed: https://github.com/ealeksandrov/EAIntroView/issues/186
