### ISSUE TITLE
pageAppeared: not called when using setCurrentPageIndex:

### ISSUE THREAD

**Issue by r-dent** [ealeksandrov/EAIntroView#189]
The delegate method `pageAppeared:` is not called when "manually" going to a page with `setCurrentPageIndex:`. The same is for `onPageDidAppear` Block in `EAIntroPage`.

Is this a bug or on purpose?

**Comment by ealeksandrov** [comment]
That should work with manual index change, I'll check when I have time.

**Comment by r-dent** [comment]
Okay. I had to use `scrollToPageForIndex:` instead of `setCurrentPageIndex:`. But the problem was that this method is not in the current Cocoapods release. The version on Cocoapods is from May.
I fixed the problem by linking directly to the latest commit in my Podfile. But i think a better solution would be to just publish the new features and fixes to Cocoapods. 😄

**Comment by ealeksandrov** [comment]
Sure, will push update on this weekend :)

But we still need to fix delegate call from `setCurrentPageIndex:`, so keep this issue open.

**Comment by ealeksandrov** [comment]
Cleaning up the issues in preparation for CocoaPods release.
For anyone having issues with `setCurrentPageIndex:animated:` - use `scrollToPageForIndex:animated:`. Difference between them and reason to split into 2 methods discussed in #144, #174, #177.

In future releases this redundancy of similar methods should be removed.

**Comment by ealeksandrov** [comment]
EAIntroView 2.10.0 pushed to CocoaPods trunk! :tada:
