### ISSUE TITLE
text size is small

### ISSUE THREAD

**Issue by rajaunleashed** [ealeksandrov/EAIntroView#198]
Hi,

All I want to scalable view or zoom in functionality that user can zoom the text scroll the text etc.

**Comment by ealeksandrov** [comment]
Sounds like a complicated thing. How about using page from custom view and add scrollview in it?

**Comment by rajaunleashed** [comment]
Actually my client wants intropages more interactive. He wants the font scalling

**Comment by ealeksandrov** [comment]
Then scrollview inside pages should work. Don't know about caveats though, view hierarchy will look pretty strange - scrollviews inside scrollview.

**Comment by rajaunleashed** [comment]
Yes I am using scroll view now

**Comment by rajaunleashed** [comment]
Hi,

I am using imageView sague in UIView but it gives me the error attached in the snapshot. Kindly guide me what does this error mean? How to get ride of this error I have to use zoom in function on the imageView but it doesn't allow me to add sague there in UIView.

Thank you
[https://drive.google.com/file/d/0B_hKG7QgB8MoVnh2QWJ1WklJVFk/view?usp=sharing](url)

[https://drive.google.com/file/d/0B_hKG7QgB8MoOEpsUkRya2EtZE0/view?usp=sharing](url)

**Comment by ealeksandrov** [comment]
Try to load that Nib in separate variable with "loadNibNamed" and check what will be in that array.
