### ISSUE TITLE
how to use xib file for show page

### ISSUE THREAD

**Issue by MansoorJafari** [ealeksandrov/EAIntroView#199]
Hi

How to use xib or storyboard page file for show page in intro

```
let page1 = EAIntroPage(customViewFromNibNamed: "IntroPage1", bundle: nil)
page1?.bgColor = UIColor.gray

```

please help.

**Comment by ealeksandrov** [comment]
Check out example project, it should be pretty simple: https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L192
