### ISSUE TITLE
Pagination Dot Color

### ISSUE THREAD

**Issue by zirkler** [ealeksandrov/EAIntroView#200]
Hi there,

how can I change the paginator dot color?

Best Regards

**Comment by ealeksandrov** [comment]
Use `pageIndicatorTintColor` and `currentPageIndicatorTintColor` properties on `UIPageControl` - [introView.pageControl](https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroView.h#L65).

For very custom dots check out [example project](https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L315-L318).
