### ISSUE TITLE
Add carthage compatibility

### ISSUE THREAD

**Issue by maxydon** [ealeksandrov/EAIntroView#204]
hello is this compatible with carthage?
I'm getting this error
`Dependency "EAIntroView" has no shared framework schemes`

**Comment by ealeksandrov** [comment]
One hacky option is:
```
introView.transform = CGAffineTransformMakeRotation(M_PI_2);
```

But I'll consider this as feature request.

**Comment by ealeksandrov** [comment]
Carthage compatibility added in e974414a213ff1d2f2b1b481f4cd8ff80293772f.
Docs updated in 364c393848abd5db41362df07593991a0bca0626.
