### ISSUE TITLE
Inserting a tableview inside a page makes it untouchable/undraggable

### ISSUE THREAD

**Issue by zfrankz** [ealeksandrov/EAIntroView#205]
Hello, I've added a tableview to a custom nib loaded page. It scrolls but when trying to select a cell is unresponsive. Same with edit actions, you can change the order of the rows but you cannot "delete" them.

I've realised that, a very long press on the table works. how can I fix it?

Any ideas?

Thank you!

**Comment by ealeksandrov** [comment]
From [Apple Docs](https://developer.apple.com/documentation/uikit/uiwebview):

> Important
> You should not embed UIWebView or UITableView objects in UIScrollView objects. If you do so, unexpected behavior can result because touch events for the two objects can be mixed up and wrongly handled.

I tried number of workarounds, but nothing worked for me.
So I'll close this for now since it's explicitly unsupported by Apple.
