### ISSUE TITLE
I want to add "NEXT" button action instead of scrolling to next page, how to call this for navigating to next page.

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [ealeksandrov/EAIntroView#208]
Thanks for your great library, its very helpful.

But, I added my custom button for navigates to next screen instead of scrolling to next, but, how to load next page with that action, can you suggest me in iOS?

**Comment by ealeksandrov** [comment]
Try `scrollToPageForIndex:animated:`
https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroView.h#L94-L95
