### ISSUE TITLE
Not calling table view didselectrow

### ISSUE THREAD

**Issue by yunitaandini** [ealeksandrov/EAIntroView#210]
hey @ealeksandrov you have nice job here, I can swipe multiple views and got the offset to do color gradation on transition. But I have a little problem here, so I insert a table view inside one of the view. It shows up the data just fine, but then when I select a row nothing happens. It can't trigger "didselectarow" override, even though I bring the tableview to front (in case, something cover it up) and set single selection. Could you elaborate more how to solve my problem? Thank you.

**Comment by ealeksandrov** [comment]
I think that's famous "scrollviews inside scrollviews" situation that can lead to strange behaviour. Can you share simple setup based on demo project to reproduce it?

**Comment by ealeksandrov** [comment]
Closing it's explicitly unsupported by Apple.
More info in #205.
