### ISSUE TITLE
Could not rounded the skip button correctly when customizing the Skip Button

### ISSUE THREAD

**Issue by crazytom26** [ealeksandrov/EAIntroView#216]
When customizing the skip button, the height is more than 40dp, and I set btn.layer.cornerRadius equals 20, and masks to bouds yes, but the btn was not rounded correctly.

**Comment by ealeksandrov** [comment]
> height is more than 40dp
what is "dp"?

> was not rounded correctly
what do you mean? anything happens or something wrong happens?

**Comment by crazytom26** [comment]
I mean when I created a button and set its frame as cgrectmake(0,0,290,66). And then I set the button.layer.cornerRadius equals to 33, and layer.maskstobound yes. And I assigned to the skip button. But the skip button was not rounded correctly. “dp “ is a unit just like pixel.

**Comment by crazytom26** [comment]
@ealeksandrov  OK, I will show my code.
` EAIntroView *intro = [[EAIntroView alloc] initWithFrame:self.window.rootViewController.view.bounds andPages:@[page1,page2,page3]];
    intro.pageControlY = 60.f;
    UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
    btn.frame = CGRectMake(0, 0, 295, 66);
    [btn setTitle:@"开始体验" forState:UIControlStateNormal];
    [btn setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    [btn setBackgroundColor:[UIColor colorWithTextName:@"red_500" alpha:0.7]];
    btn.layer.cornerRadius = 66/2.0;
    btn.layer.masksToBounds = YES;
    intro.skipButton = btn;
    intro.skipButtonY = 180.f;
    intro.skipButtonAlignment = EAViewAlignmentCenter;`

The skip button should be like round but actually it was not. It like this shape: < >. 
![image](https://user-images.githubusercontent.com/12843351/33941058-3a70fec2-e04c-11e7-8774-c60fe7799a00.png)

**Comment by xwgit2971** [comment]
+ 1

**Comment by crazytom26** [comment]
Cause the author didn't reply to this issues again, I will give it up and do not use this pod,and write it by myself.

**Comment by ealeksandrov** [comment]
>  write it by myself

instead of fixing issue and writing PR you want to rewrite everything from scratch?

I'm not paid tech support, will look into it when I have free time after work. No deadlines promised.

**Comment by ealeksandrov** [comment]
Intro view frame laid out with auto layout and it respects its intrinsic size if no additional constraints are added. Setting button's frame is useless.

Add width and height constraints:

```obj-c
[intro addConstraint:[NSLayoutConstraint constraintWithItem: btn
                                                  attribute: NSLayoutAttributeWidth
                                                  relatedBy: NSLayoutRelationEqual
                                                     toItem: nil
                                                  attribute: NSLayoutAttributeNotAnAttribute
                                                 multiplier: 1.0
                                                   constant: 295]];
[intro addConstraint:[NSLayoutConstraint constraintWithItem: btn
                                                  attribute: NSLayoutAttributeHeight
                                                  relatedBy: NSLayoutRelationEqual
                                                     toItem: nil
                                                  attribute: NSLayoutAttributeNotAnAttribute
                                                 multiplier: 1.0
                                                   constant: 66]];
```

<img width="447" alt="screen shot 2017-12-19 at 20 25 50" src="https://user-images.githubusercontent.com/3132438/34170197-057f8c02-e4fb-11e7-9451-e2455334aeaa.png">

**Comment by crazytom26** [comment]
@ealeksandrov  Thx, I just customized the Button which was based on your pods, but then you gave a better way to fix my problem, so I think what I put up should not be a problem, it supports .
