### ISSUE TITLE
Scroll of desc(if I have large text)

### ISSUE THREAD

**Issue by kalpacse96** [ealeksandrov/EAIntroView#221]
How should I scroll the desc view if I have large text. _scrollingEnabled_ is not working for me.

**Comment by ealeksandrov** [comment]
This is not something straightforward to do but you can create custom page with scrollview inside - [EAIntroPage.m custom view init](https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroPage.m#L51-L69).
