### ISSUE TITLE
Crash if scrolling while dealloc

### ISSUE THREAD

**Issue by BarakRL** [ealeksandrov/EAIntroView#42]
if the view is dealloced while still scrolling it will crash with:
EXC_BAD_ACCESS
on:
[UIScrollView(UIScrollViewInternal) _delegateScrollViewAnimationEnded]

I've came across these kind of exceptions before in other controls and even in UICollectionView (just gooogle: _delegateScrollViewAnimationEnded).

This issue can be fixed easily by setting the scrollView.delegate to nil on dealloc:

-(void)dealloc {
    self.scrollView.delegate = nil;
}

**Comment by ealeksandrov** [comment]
Closed until further details or reproduced demo.
