### ISSUE TITLE
Transition to autolayout

### ISSUE THREAD

**Issue by dorinsimina** [ealeksandrov/EAIntroView#64]
There are any plans to support layout constraints for all UI elements (e.g title and description)? For example, in an iPad could be useful to have a full support for portrait/landscape.

**Comment by ealeksandrov** [comment]
Switch from autoresizing masks to autolayout constraints. Support iOS 7 and up.

**Comment by caramdache** [comment]
Thanks Evgeny  I am looking forward to 3.0. 

Caram

**Comment by ealeksandrov** [comment]
Thanks to @XBeg9 for https://github.com/XBeg9/EAIntroView/commit/8e7cb8a17f4d799881b73d9ede3b2d70ed97d760 - here is some improvements inspired by it: 11f4d7751bd6576b3f3ac007c5cf4f8d84f7fd53

Custom skipButton positioning is wrong right now (always remain default), but whole structure is much better. After dealing with it I will make version 2.7 with most fixes and then will drop iOS 6 and remove all related hacks.

For 3.0 I am considering simple autolayout by default with unlimited customisation.

**Comment by ealeksandrov** [comment]
More work on fixing constraints: 70431dbfde42ce187c023f01bf05fd1a3e5a08ec
Now custom skipButton fully supported.

**Comment by williamsjj** [comment]
We're currently using a custom view for each page and those custom views are auto-layout internally.

**Comment by wuf810** [comment]
Any news on support for auto layout i.e. I'm using my own custom views for pages and really could do with auto layout constraints working?

**Comment by ealeksandrov** [comment]
You already can use autolayout internally in your views. What problems are you experiencing?

**Comment by wuf810** [comment]
Thanks for reply. Sadly none of my constraints are being used. Everything is place to left of the view regardless. Is there anything I need to set or turn off? I assumed auto layout was not working because your demo custom view XIB doesn't have it turned on. So you are saying it should just work ?

**Comment by ealeksandrov** [comment]
Yes, if you are using page views from own xibs - try to enable autolayout there.
I haven't done this personally, but in the discussion above people are using it.

I can't get further on implementing and testing full autolayout support because I am waiting for feedback on some bugs. Anyway, autolaoyut is top priority task for me and it would be done soon. Demo project will be updated too.

**Comment by wuf810** [comment]
Thanks, I'll have another go and see how I get on. Thanks again for a great framework.

**Comment by ealeksandrov** [comment]
Dropped autoresizing masks and fully switched to auto layout in 7b245c11fa3f5159f2a38de0b70f6273ec223ab9.
Will continue to test rotation and resizing in #79.
Please test `:head` and share how it can be improved.
