### ISSUE TITLE
Disable/re-enable scrolling during presentation

### ISSUE THREAD

**Issue by tschleuss** [ealeksandrov/EAIntroView#65]
Hi, can i do something like this ?

I have 4 pages, but on page 3 i want user press a button for go to the last page, blocking if they try to swipe.

**Comment by ealeksandrov** [comment]
Had to create specialised `UIScrollView` subclass - [EARestrictedScrollView](https://github.com/ealeksandrov/EARestrictedScrollView).
Scrolling in `EAIntroView` now can be limited in 2 ways:
1. Setting [`scrollingEnabled`](https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroView.h#L67) to NO limits scrolling only on current page (can't go previous or next page).
2. Using [`limitScrollingToPage:`](https://github.com/ealeksandrov/EAIntroView/blob/master/EAIntroView/EAIntroView.h#L79) limits scrolling from 1st page to selected page (can go previous pages, but not next).

Example added to demo project: [ViewController.m#L334](https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L334)

**Comment by allaire** [comment]
This broke `:head` for me

**Comment by ealeksandrov** [comment]
@allaire what problems are you experiencing? Demo project seems to work fine.

**Comment by ealeksandrov** [comment]
@allaire ping

**Comment by allaire** [comment]
Will report soon, sorry

**Comment by ealeksandrov** [comment]
@allaire pong :)

**Comment by allaire** [comment]
Will try with :head again today, sorry about the delay :)

**Comment by ealeksandrov** [comment]
Appreciate your feedback. Keep in mind that `:head` is little broken for rotation and resizing, it is WIP.

**Comment by Amaneo** [comment]
[ViewController.m#L334](https://github.com/ealeksandrov/EAIntroView/blob/master/Example/Source/ViewController.m#L334) 
it did not work for me in swift 
error :  Cannot assign value of type 'UInt' to type 'Int'

**Comment by ealeksandrov** [comment]
@Amaneo  you are referencing obj-c example. Can you provide exact code that is not working?

**Comment by Amaneo** [comment]
page5.onPageDidAppear = {() -> Void in
 self.intro.limitPageIndex = intro.visiblePageIndex
}
