### ISSUE TITLE
Button is not clickable in `titleView`

### ISSUE THREAD

**Issue by babygau** [ealeksandrov/EAIntroView#7]
Here is my situation.
I managed to display my button in the titleView. But somehow the button is not fired when I click on it. 
The titleView is created by my custom view from an xib file. I even tried it with a callback method but no luck
How to fix this issue?

**Comment by temasnow** [comment]
Hi! 
When I try to set the position of a button, button is not clickable.

**Comment by ealeksandrov** [comment]
Hey,
can you share example with this bug?

**Comment by ealeksandrov** [comment]
Maybe you are talking about #129?

**Comment by ealeksandrov** [comment]
Feel free to reopen with example code if you still have this issue.

**Comment by PurviJani** [comment]
Hey I am facing same problem the custom button which is not clickable just because of the size of custom view is not changing. Even i tried to directly add the custom button in titleview but i couldn't make it. please help me. Here is my example code,
 UIView *myView = [[UIView alloc] initWithFrame:CGRectMake(20.0, 200.0, 280.0, 45.0)];
    myView.userInteractionEnabled = YES ;
    myView.backgroundColor = [UIColor redColor];

    
    UIButton *button = [UIButton buttonWithType:UIButtonTypeRoundedRect];
    [button addTarget:self
               action:@selector(MyAction:)
     forControlEvents:UIControlEventTouchUpInside];
    [button setTitle:@"CONTINUE" forState:UIControlStateNormal];
    button.frame = CGRectMake(20.0, 580.0, 280.0, 45.0);
    button.backgroundColor = [UIColor colorWithRed:10.0f/255.0f green:144.0f/255.0f blue:203.0f/255.0f alpha:1.0f];
     button.titleLabel.font = [UIFont fontWithName:@"Helvetica Neue" size:16];
    [button setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
    button.userInteractionEnabled = YES;
//    button.layer.cornerRadius = 5;
    [myView addSubview:button];
   

    intro.swipeToExit = NO ;
    intro.skipButton = nil ;
    intro.titleView = myView;
   


**# Button Action:** 

-(void)MyAction:(UIButton *)sender
{
    [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"isIntro"];
    [self performSegueWithIdentifier:@"SignUpVC" sender:self];
}

**Comment by ealeksandrov** [comment]
You have title view with height 45.0, but inserting button on Y = 580.0.
If you change button origin to (0,0) it will work perfectly:
![screen shot 2016-10-09 at 01 37 27](https://cloud.githubusercontent.com/assets/3132438/19216360/03e12bcc-8dc1-11e6-967f-f72c3bbc66d5.png)

**Comment by PurviJani** [comment]
Thanks but i want button downwards ! if i am setting frame of button it comes to the perfect place but button is not clicked (touch up inside method is not called). Please help me.
![img_0517](https://cloud.githubusercontent.com/assets/22657317/19231667/ef1d1cbc-8ef8-11e6-940a-58ae81874abc.PNG)

**Comment by ealeksandrov** [comment]
Don't move button to the bottom, move the whole title view.

**Comment by PurviJani** [comment]
Thank you so much it works perfectly but only with static values !

**Comment by ealeksandrov** [comment]
I will consider improving `titleView` layout for simpler customization.

**Comment by PurviJani** [comment]
Hey i want to set title at Top above the image but it doesn't work can you please help me?
![screen shot 2017-05-16 at 12 10 15 pm](https://cloud.githubusercontent.com/assets/22657317/26092941/2eeadf44-3a31-11e7-8d48-4d9a5ec000c8.png)
![screen shot 2017-05-16 at 12 14 41 pm](https://cloud.githubusercontent.com/assets/22657317/26092957/3e90541a-3a31-11e7-9499-1c675ee0fb1e.png)

**Comment by riyanpratama** [comment]
@PurviJani you can use your custom view or just create your xib for the pages, then load as `EAIntroPage`

`EAIntroPage *page = [EAIntroPage pageWithCustomView:yourCustomView];`
