### ISSUE TITLE
Why we cannot just set skip button title?

### ISSUE THREAD

**Issue by ArtworkAD** [ealeksandrov/EAIntroView#84]
Do I have to create a custom button just to set the title from "Skip" to "Skip now" ? Because

    introView.skipButton.titleLabel?.text = "Skip now" 

is not working.

**Comment by ealeksandrov** [comment]
`skipButton.titleLabel.text` is readonly, you should be using [`setTitle: forState:`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIButton_Class/index.html#//apple_ref/occ/instm/UIButton/setTitle:forState:)
Added a demo in 5a41ef2cc778355d90fa2e7fb3978bf80f70c7cd.
