### ISSUE TITLE
buildUI should not set black background

### ISSUE THREAD

**Issue by ArtworkAD** [ealeksandrov/EAIntroView#85]
In EAIntroView.m, line 185 in buildUI method the background color should not be black. Set it to clearColor or make it customizable

    self.backgroundColor = [UIColor clearColor];

It's a step forward to achieve this: https://github.com/ealeksandrov/EAIntroView/issues/71

**Comment by ealeksandrov** [comment]
In d5c796e484f2a6109a8d1129dc99d49c18d0a529 backgroundColor now is `clearColor` if any page's `alphaValue` is different from `1.0`. Default is still `blackColor` to preserve original appearance.

Remember that it could be changed outside of EAIntroView implementation (`intro.backgroundColor`).
