### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by popoko** [ealeksandrov/EAIntroView#88]
I downloaded this class of zip, And I established 4 classes to Xcode project.
When I build my project, it became fail.
Failed cause is EAIntroPage.h.
I want to download the source that has been modified.
Or, please tell me how do fix this code.
version:
Xcode6.1.1
OS X Yosemite 10.10.1

**Comment by ealeksandrov** [comment]
Please provide build error description.
I just tested latest repo version on Xcode6 + Yosemite and demo project is working ok.

**Comment by popoko** [comment]
This is my build error messages.

//------------------------------------
/fakepath/EAIntroView/EAIntroPage.h:13:31: Unknown type name 'UIImage'
/fakepath/EAIntroView/EAIntroPage.h:13:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:29:31: Unknown type name 'UIView'
/fakepath/EAIntroView/EAIntroPage.h:29:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:31:31: Unknown type name 'CGFloat'
/fakepath/EAIntroView/EAIntroPage.h:33:31: Unknown type name 'UIFont'
/fakepath/EAIntroView/EAIntroPage.h:33:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:34:31: Unknown type name 'UIColor'
/fakepath/EAIntroView/EAIntroPage.h:34:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:35:31: Unknown type name 'CGFloat'
/fakepath/EAIntroView/EAIntroPage.h:38:31: Unknown type name 'UIFont'
/fakepath/EAIntroView/EAIntroPage.h:38:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:39:31: Unknown type name 'UIColor'
/fakepath/EAIntroView/EAIntroPage.h:39:1: Property with 'retain (or strong)' attribute must be of object type
/fakepath/EAIntroView/EAIntroPage.h:40:31: Unknown type name 'CGFloat'
/fakepath/EAIntroView/EAIntroPage.h:41:31: Unknown type name 'CGFloat'
/fakepath/EAIntroView/EAIntroPage.h:45:31: Unknown type name 'CGFloat'
/fakepath/EAIntroView/EAIntroPage.h:53:31: Unknown type name 'UIView'
/fakepath/EAIntroView/EAIntroPage.h:53:1: Property with 'retain (or strong)' attribute must be of object type
//------------------------------------

I really appreciate it.

**Comment by ealeksandrov** [comment]
Try adding `#import <UIKit/UIKit.h>` to the top of `EAIntroPage.h`

**Comment by popoko** [comment]
Build is succeeded!
A thousand thanks for your kindness.
And, I'm sorry to my easy mistake.

**Comment by ealeksandrov** [comment]
:+1:
It's not your mistake, I'll add this import to source.
