### ISSUE TITLE
Skip button behaving strangely

### ISSUE THREAD

**Issue by pawelkata** [ealeksandrov/EAIntroView#90]
Hello,

First of all thanks for a great lib. It's been a blast to use.

Anyways, I've encountered a small and strange problem: the skip button is doubled on every EAIntroPage, making animations work very strangely. To add to the above, it doesn't disappear when showSkipButtonOnlyOnLastPage is set to true.

Here's a picture below of what's happening:

![img_8366](https://cloud.githubusercontent.com/assets/962904/5679749/1b4bd730-9804-11e4-9fa4-96ec8e586440.PNG)

I'm using pages created in xib's.

Any idea on what might be happening?

**Comment by ealeksandrov** [comment]
Can you provide some code or example project? I tried this in demo app and it is working normally:
``` obj-c
- (void)showIntroWithCustomViewFromNib {
    EAIntroPage *page1 = [EAIntroPage pageWithCustomViewFromNibNamed:@"IntroPage"];
    EAIntroPage *page2 = [EAIntroPage pageWithCustomViewFromNibNamed:@"IntroPage"];
    EAIntroPage *page3 = [EAIntroPage pageWithCustomViewFromNibNamed:@"IntroPage"];
    EAIntroPage *page4 = [EAIntroPage pageWithCustomViewFromNibNamed:@"IntroPage"];
    page1.bgImage = [UIImage imageNamed:@"bg1"];
    page2.bgImage = [UIImage imageNamed:@"bg2"];
    page3.bgImage = [UIImage imageNamed:@"bg3"];
    page4.bgImage = [UIImage imageNamed:@"bg4"];
    
    EAIntroView *intro = [[EAIntroView alloc] initWithFrame:rootView.bounds andPages:@[page1,page2,page3,page4]];
    
    [intro setShowSkipButtonOnlyOnLastPage:YES];
    [intro showInView:rootView animateDuration:0.3];
}
```

**Comment by pawelkata** [comment]
The thing is, I'm not doing any fringe implementations either. My exact code is this (I have an UIView with backgroundColor set up as each nib's background):

```
UIView *rootView = self.tabBarController.view;

EAIntroPage *page1 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial1"];
EAIntroPage *page2 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial2"];
EAIntroPage *page3 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial3"];
EAIntroPage *page4 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial4"];
EAIntroPage *page5 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial5"];
EAIntroPage *page6 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial6"];
EAIntroPage *page7 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial7"];
EAIntroPage *page8 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial8"];
EAIntroPage *page9 = [EAIntroPage pageWithCustomViewFromNibNamed:@"Tutorial9"];

EAIntroView *intro = [[EAIntroView alloc] initWithFrame:rootView.bounds andPages:@[page1, page2, page3, page4, page5, page6, page7, page8, page9]];
intro.backgroundColor = [UIColor colorWithRed:0.16 green:0.42 blue:0.68 alpha:1];
[intro setDelegate:self];

[intro showInView:rootView animateDuration:1.0];
```

My whole view hierarchy setup is this:
```
Application Window
┗ CJPAdController
  ┗ UITabBarController.
    ┗ Tab#1: UINavigationController
    ┗ Tab#2: UINavigationController
    ┗ Tab#3: UINavigationController
```

I'm on iOS8 and i'm using auto layout. I already spent 2 hours trying to fix this, but no cigar.

It's by no means backbreaking and it was working properly in my other projects, but this particular situation is very strange... especially the skip button cloning.

**Comment by ealeksandrov** [comment]
I made the same setup, even with `CJPAdController`, but I can't see this bug.

Please check it out: https://github.com/ealeksandrov/IntroTest. Add there your xibs or anything else to reproduce the bug. Also you can send your example project to me by email privately (you can find address in my GitHub profile).

**Comment by pawelkata** [comment]
@ealeksandrov I tested your solution and it's working great. Then I added two of my own xib's and it started happening again, but only on my xib's. At first I thought it was an auto layout issue, but removing constraints from one of my xib's didn't fix the problem. Then I thought it was my setup (I had an additional container view for background color in my xib files), but removing it didn't change anything.

Here's a zip with my setup -- maybe you'll work something out:

https://dl.dropboxusercontent.com/u/149880/IntroTest.zip

**Comment by ealeksandrov** [comment]
![screenshot 2015-01-13 00 11 31](https://cloud.githubusercontent.com/assets/3132438/5711072/c27e2f38-9ab8-11e4-9c0c-0324fad54f83.png)
Every page is instance of EAIntroView itself! :smile:
Just clear this field (use plain UIView there) and it will work normally.

I will think about more clear way to use EAIntroView in IB.

**Comment by pawelkata** [comment]
Oh man, such an omission on my side. Not only I intended it to be EAIntroPage (stupid autofill!), but also it was redundant. Anyway, thank you kindly for your time. This is a great library!
