### ISSUE TITLE
Show under navigation bar in Swift

### ISSUE THREAD

**Issue by allaire** [ealeksandrov/EAIntroView#95]
See screenshot: https://dl.dropboxusercontent.com/s/tuxgpwnhxecbncj/2015-01-25%20at%204.05%20PM.png?dl=0

Related code in `viewDidLoad`:

```swift
        var page1 = EAIntroPage()
        page1.title = "Title 1"
        page1.desc = "Page 1 description"
        
        var page2 = EAIntroPage()
        page2.title = "Title 2"
        page2.desc = "Page 2 description"
        
        let rect = CGRectMake(0, 0, self.navigationController!.view.frame.width, self.navigationController!.view.frame.height)
        var introView = EAIntroView(frame:rect, andPages: [page1, page2])
        introView.showInView(self.navigationController!.view, animateDuration: 0.3)
```

**Comment by allaire** [comment]
@ealeksandrov I found a solution:

```swift
            let window = UIApplication.sharedApplication().keyWindow
            let rect = CGRectMake(0, 0, self.navigationController!.view.frame.width, self.navigationController!.view.frame.height)
            var introView = EAIntroView(frame:window!.bounds, andPages: [page1, page2])
            introView.showInView(window, animateDuration: 0.3)
```

**Comment by allaire** [comment]
@ealeksandrov More insights: if I hide the back button, it works:

`navigationItem.hidesBackButton = true`

**Comment by ealeksandrov** [comment]
Really strange. Your code is ok, nothing criminal.
I will try to reproduce your issue when I have time. Also I am thinking about adding `showFullscreen` method to encapsulate all the logic about finding topmost viewcontroller. Stay tuned.

**Comment by allaire** [comment]
Hope that I'm not a criminal :)

What do you think of the window solution `UIApplication.sharedApplication().keyWindow`?

**Comment by ealeksandrov** [comment]
Yes, I think this is ok :)
Looks like buggy `navigationController` and you found a workaround.

**Comment by ealeksandrov** [comment]
In 81c1f612f3c8c8dbbc434e55b1436d68de60b54b I added [`showFullscreen`](https://github.com/ealeksandrov/EAIntroView/blob/81c1f612f3c8c8dbbc434e55b1436d68de60b54b/EAIntroView/EAIntroView.h#L72-74) set of actions. It will find topmost window and show intro there.

**Comment by allaire** [comment]
Cool thanks @ealeksandrov, Any reason why not simply pick the active keyWindow ?

**Comment by ealeksandrov** [comment]
The `keyWindow ` is the window that is currently accepting mouse and keyboard events. It is not guranteed to be topmost displayed window.
BTW snippet for window selection is taken from [SVProgressHUD](https://github.com/TransitApp/SVProgressHUD), which worked perfectly for me for a long time.
