### ISSUE TITLE
ScrollView autoresize

### ISSUE THREAD

**Issue by crazyramirez** [ealeksandrov/EAIntroView#96]
self.scrollView.autoresizingMask =
    UIViewAutoresizingFlexibleBottomMargin |
    UIViewAutoresizingFlexibleHeight |
    UIViewAutoresizingFlexibleLeftMargin |
    UIViewAutoresizingFlexibleRightMargin |
    UIViewAutoresizingFlexibleTopMargin |
    UIViewAutoresizingFlexibleWidth;

(EAIntroView.m) Fixed size for iOS versions prior to autolayout

**Comment by ealeksandrov** [comment]
Current `:head` is somehow broken without autolayout?
I will test this case soon, but some time ago scrollview resized well on rotations.

**Comment by ealeksandrov** [comment]
Autoresizing masks now dropped. Supporting only iOS7 and up. If this can be a bugfix for previous `EAIntroView` version - please clarify.
Thanks.
