### ISSUE TITLE
EARestrictedScrollView used but not defined

### ISSUE THREAD

**Issue by caramdache** [ealeksandrov/EAIntroView#98]
Evgeny, seems you're now using your new EARestrictedScrollView class but it's not defined. Workout is to fetch it from your other repository but it makes the compilation clumsy. I'm using EAIntroView from RM, as a vendored project, so it is difficult for me to add additional include directories.

Caram

**Comment by ealeksandrov** [comment]
Thanks, I will thinks about ways to simplify it. How about git submodule support?
>I'm using EAIntroView from RM

What is `RM`?

**Comment by caramdache** [comment]
RubyMotion.
Hmm… a copy of the file in the EAIntroView directory would be nice, if possible.

Caram

**Comment by ealeksandrov** [comment]
> a copy of the file in the EAIntroView directory

This needs update of `EAIntroView` for every bugfix or improvement in `EARestrictedScrollView`.
I will think about it, thanks for suggestion.

**Comment by ealeksandrov** [comment]
Mentioned dependency explicitly in README: 5abc8793e6f63183e76d0e07822b6b9baa29707c
Moving this custom class here would be bad style and strong coupling.
