### ISSUE TITLE
Current commit (141) doesn't properly resize/reposition when rotating.

### ISSUE THREAD

**Issue by funnel20** [ealeksandrov/EAIntroView#99]
I have successfully implemented 2.7.0 in my project (commit 139; https://github.com/ealeksandrov/EAIntroView/commit/c3e18feea82d135cbe6defa749bcbbf52b9cf5b9).

I show the EAIntroView in a view by using:
[guidedIntroduction showInView:self.navigationController.view animateDuration:0.5];

When I start in landscape everything is shown:
![screen shot 2015-02-24 at 11 28 06](https://cloud.githubusercontent.com/assets/2139844/6347604/8a416aea-bc19-11e4-8b73-0fc05adcf7e0.png)

When rotating to portrait, resizing of the background frame is correct (except for my custom button and image):
![screen shot 2015-02-24 at 11 28 28](https://cloud.githubusercontent.com/assets/2139844/6347610/97453eec-bc19-11e4-8a30-696de952ed8a.png)

I updated to the latest commit (141; https://github.com/ealeksandrov/EAIntroView/commit/7b245c11fa3f5159f2a38de0b70f6273ec223ab9).

Repeating the same test shows background frame that's not resized (part of the underlying tableview controller is visible at the bottom). Also the position of the default items is incorrect:
![screen shot 2015-02-24 at 11 30 27](https://cloud.githubusercontent.com/assets/2139844/6347616/a034f90c-bc19-11e4-897a-6231a4c81565.png)

Do I something wrong, or is something broken in the last commit?

**Comment by ealeksandrov** [comment]
Thanks for feedback.
I am still working on rotation and resizing support, it is not tested at all. Will investigate your case today.

**Comment by funnel20** [comment]
Hi,

No problem, I reverted to the previous version, which works properly for the rotation.

Only what I can't get working is to properly reposition my custom views (like the logo) after rotation.
I tried with autoresizingMask property, but whatever options I provide, it doesn't work.

What I do is:

// Create logo:
UIImageView *dutchovateLogo = [[UIImageView alloc] initWithImage:[UIImage imageNamed: @"DutchovateLogo"]];
[dutchovateLogo setFrame:CGRectMake(([UIScreen mainScreen].bounds.size.width - 238.0)/2, [UIScreen mainScreen].bounds.size.height - 280.0, 238.0, 68.0)];
    
// Add logo:
page1.subviews = @[dutchovateLogo];

Do you have any suggestion?

Thanks

**Comment by ealeksandrov** [comment]
Can't say much right now, need to test and fix current `:head`. I will let you now about results.

**Comment by ealeksandrov** [comment]
Why don't you use `page.titleIconView` for your logo? It will be centered automatically.
I fixed backgrond sizing in `:head` to work as you describe, but full autolayout support is blocked by #100. Lets continue discussing rotation issue in #79.

**Comment by funnel20** [comment]
I verified the fix (commit 142), this works.
And I used page.titleIconView for the logo, thanks for the tip.
